
Exception::getLine

(PHP 5 >= 5.1.0, PHP 7)

Exception::getLine — 获取发生异常的代码在文件中的行号

说明

final public int Exception::getLine ( void )

返回发生异常的代码在文件中的行号。

参数

此函数没有参数。

返回值

返回发生异常的代码在文件中的行号。

范例

Example #1 Exception::getLine()示例

<?php
try {
    throw new Exception("Some error message");
} catch(Exception $e) {
    echo "The exception was thrown on line: " . $e->getLine();
}
?>

以上例程的输出类似于：

The exception was thrown on line: 3


User Contributed Notes 1 note

===============================================================================

Note that it appears to be the line number the Exception was created that is
returned, *not* the line it was thrown from.

See this bug:
http://bugs.php.net/bug.php?id=53882

Wanted to note that here until documentation is fixed or bug report dealt with.
