
Yaf_Dispatcher::catchException

(Yaf >=1.0.0)

Yaf_Dispatcher::catchException — 开启/关闭自动异常捕获功能

说明

public Yaf_Dispatcher Yaf_Dispatcher::catchException ([ bool $flag ] )

当 application.dispatcher.throwException 开启的时候（你也可以通过调用 
Yaf_Dispatcher::throwException(TRUE)() 来开启它），Yaf将会抛出异常而不是触发异
常发生。

如果开启了 Yaf_Dispatcher::catchException() （可以通过设置
application.dispatcher.catchException来开启），并且在你定义了异常处理的
controller的情况下，Yaf会将所有未捕获的异常交给Error Controller的Error Action来
处理。

参数

flag

    bool

返回值

范例

Example #1 Yaf_Dispatcher::catchException()example

/* if you defined a ErrorController like following */
<?php
class ErrorController extends Yaf_Controller_Abstract {
     /** 
      * you can also call to Yaf_Request_Abstract::getException to get the 
      * un-caught exception.
      */
     public function error($exception) {
        /* error occurs */
        switch ($exception->getCode()) {
            case YAF_ERR_NOTFOUND_MODULE:
            case YAF_ERR_NOTFOUND_CONTROLLER:
            case YAF_ERR_NOTFOUND_ACTION:
            case YAF_ERR_NOTFOUND_VIEW:
                echo 404, ":", $exception->getMessage();
                break;
            default :
                $message = $exception->getMessage();
                echo 0, ":", $exception->getMessage();
                break;
        }
     } 
}
?>

以上例程的输出类似于：

/* now if some error occur, assuming access a non-exists controller(or you can throw a exception yourself): */
404:Could not find controller script **/application/controllers/No-exists-controller.php

参见

  • Yaf_Dispatcher::throwException() - 开启/关闭异常抛出
  • Yaf_Dispatcher::setErrorHandler() - 设置错误处理函数

